[package]
name = "oliver_explorer"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["blocking"] }
scraper = "0.17.1" 
url = "2.4.0"
eframe = "0.31.1"
egui_extras = { version = "0.31.1", features = ["default", "image"] }